name: create-pull-request
on: 
  push:
    branches: [ "develop" ]

jobs:
  label:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"